name: subtree-matrix

on: [push]

jobs:
  sync-downstream:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        extension:
          - workflow-ext

    name: Update extension ${{ matrix.extension }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
          ssh-key: '${{ secrets.DOWNSTREAM_GITHUB_DEPLOY_KEY }}'
      - name: Push subtree changes to ${{ matrix.extension }}
        run: |
          git subtree push --prefix=ext/${{ matrix.extension }} git@github.com:bechte/${{ matrix.extension }}.git release/${{ github.ref_name }}
